### ISSUE TITLE
make generic

### ISSUE THREAD

**Issue by jgroom33** [ansible-collections/vmware_rest_code_generator#6]
##### SUMMARY
This tool should be a generic translator to convert swagger spec to ansible modules

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
N/A

##### ADDITIONAL INFORMATION
Currently, the tool has several vmware specific implementations.

Recommended changes:
* input swagger specs from multiple directories
* output modules to multiple directories
* deprecate usage of operationId (use REST verb)

**Comment by jgroom33** [comment]
i've taken some steps to do this and will have a PR to review shortly. Though, it probably won't be a PR and should probably be a new project

**Comment by goneri** [comment]
Do you have a public branch somewhere? I'm curious to see what you've already done.

**Comment by jgroom33** [comment]
https://github.com/jgroom33/vmware_rest_code_generator

**Comment by goneri** [comment]
This is really cool, thanks for sharing.

**Comment by jgroom33** [comment]
i thought it would be better to create a separate project that is a generic swagger->collection conversion. Otherwise, all the method names change for the vmware collection.

**Comment by goneri** [comment]
We can either converge vmware_rest_code_generator toward a more generic tool, or build a generic tool and rewrite vmware_rest_code_generator to make use of it.

I would go with the first approach because we can benefit from the vmware.vmware_rest function tests and this way, we can iterate and spot regression sooner as soon as possibe.

I've no strong opinion, especially because I currently don't have time to dedicate on that. I would like to finish up a first 1.0.0 release of vmware.vmware_rest before anything.

**Comment by jgroom33** [comment]
i dont have time to break the changes into multiple PRs currently.

**Comment by jgroom33** [comment]
the vmware server has a few operations that require some specific handlings. I think this is the path forward:
1. Create a new generic code converter that handles the swagger petstore definition
2. Add handlings for customized vmware server
3. Deprecate this repo

It would be nice if this existed, but it would need to be driven by Redhat.

I can contribute to the generic converter when that is started.
